# Generated by Django 4.2.16 on 2024-11-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('motdepasse', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=15, verbose_name='Numéro de téléphone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.EmailField(max_length=15, unique=True)),
                ('motdepasse', models.CharField(max_length=100)),
            ],
        ),
    ]
