# Generated by Django 4.2.16 on 2024-11-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_rename_motdepasse_userprofile_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vip',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
