# Generated by Django 4.2.16 on 2024-11-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_vip_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='withdrawAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=100)),
                ('compte', models.CharField(max_length=20)),
                ('reseau', models.CharField(choices=[('momo', 'MTN-MOMO'), ('moov', 'MOOV'), ('orange', 'Orange')], default='momo', max_length=8, verbose_name='reseau')),
            ],
        ),
    ]
