# Generated by Django 4.2.16 on 2024-12-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_withdrawaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='revenu',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='solde',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
